// Preguntas
var q = [
	'¿Qué entiendes que otros no?',
	'¿Por qué tendrás éxito?',
	'¿Qué tan grande es la oportunidad?',
	'¿Qué problemas/obstáculos estás anticipando?',
	'¿Quién usaría tu producto?',
	'¿Cuánto cuesta la adquisición de clientes?',
	'¿Cómo ganarás dinero?',
	'¿Cuánto dinero podrías ganar por año?',
	'¿Cuántos usuarios tienes?',
	'¿Cuál es tu tasa de crecimiento de usuarios?',
	'¿Cuántos usuarios están pagando?',
	'¿Cómo estás encontrando clientes?',
	'¿Cómo entiendes las necesidades de los clientes?',
	'¿Cómo conseguirás usuarios?',
	'¿A quién contratarías o cómo agregarías a tu equipo?',
	
	'¿En qué estás trabajando?',
	'¿Tienes una demo?',
	'¿Dónde está la ciencia avanzada aquí?',
	'¿Cómo funciona tu producto en detalle?',
	'¿En qué se diferencia tu producto?',
	'¿Qué sigue? ¿Qué vas a hacer despues?',
	'¿Qué hay de nuevo en lo que haces?',
	'¿Qué, exactamente, te hace diferente de las opciones existentes?',
	'¿Quién necesita lo que estás haciendo?',
	'¿Cómo sabes que los clientes necesitan lo que estás haciendo?',
	'¿Por qué no está alguien ya haciendo esto?',
	'¿Qué obstáculos enfrentarás y cómo los superarás?',
	'¿Cómo se enterarán de ti los clientes y/o usuarios?',
	'¿Qué resistencia tendrán para probarte y cómo la superarás?',
	'¿Cuáles son las cosas clave sobre tu campo que los forasteros no entienden?',
	'¿Qué parte de tu proyecto construirás primero?',
	'¿Quién será tu primer cliente que pague?',
	'Si tu startup tiene éxito, ¿en qué áreas adicionales podrías expandirte?',
	'¿Por qué elegiste esta idea?',
	'¿Qué has aprendido hasta ahora trabajando en tu producto?',
	'En seis meses, ¿cuál será tu mayor problema?',
	'¿De dónde vienen los nuevos usuarios?',
	'¿Cómo es tu crecimiento?',
	'¿Cuál es la tasa de conversión?',
	'¿Qué hace que los nuevos usuarios te prueben?',
	'¿Por qué los usuarios reticentes se abstienen?',
	'¿Cuáles son las principales cosas que los usuarios quieren?',
	'¿Qué te ha sorprendido del comportamiento de los usuarios?',
	'¿Qué cosa impresionante has hecho?',
	'¿Qué entiendes sobre tus usuarios?',
	'¿Por qué elegiste esta idea para trabajar?',
	'¿Qué experiencia en el dominio tienes?',
	'¿Quiénes son tus competidores?',
	'¿Quiénes podrían convertirse en competidores?',
	'Alguien nos mostró una idea como esta justo antes de ustedes. No me gusta. ¿Qué más tienen?',
	'¿Qué competencia temes más?',
	'¿Cuál es tu estrategia de distribución?',
	'¿Cómo se conoció tu equipo?',
	'¿Por qué se reunió tu equipo?',
	'¿Quién en tu equipo hace qué?',
	'¿Quién es "el jefe"?',
	'¿Qué harás si no te financiamos?',
	'¿Te mudarías a Silicon Valley?',
	'¿Cómo sabemos que tu equipo se mantendrá unido?',
	'¿Qué más han creado juntos?',
	'¿Están abiertos a cambiar su idea?',
	'¿Qué sistemas has hackeado?',
	'¿Cuéntanos sobre un problema difícil que hayas resuelto?',
	'¿De qué maneras eres ingenioso?',
	'¿Te reincorporarías como una empresa estadounidense?',
	'¿Tu equipo perseverará en esto?',
	'¿Cuéntanos algo sorprendente que hayas hecho?',
	'¿Cuál es la cosa más divertida que te ha pasado?',
	'¿Cuál es la peor cosa que te ha pasado?',
	'¿Cuál es el mayor error que has cometido?',
	'¿Cuál es tu tasa de quema?',
	'¿Cuánto tiempo puedes continuar antes de financiarte?',
	'¿Cuál es el siguiente paso en la evolución del producto?',
	'¿Has recaudado fondos?',
	'¿Quién sería tu próximo contratación?',
	
	'¿Cómo sabes que la gente quiere esto?',
	'¿Qué sabes sobre este espacio/producto que otros no saben?'
];

// Consejos
var tips = [
	'Intenta tener respuestas rápidas y concisas.',
	'Intenta responder en 2 a 3 oraciones.',
	'Responde como lo harías en una conversación, esto no es una presentación.',
	'Al hablar con PG y los otros socios de YC, sé sustancial y ve directo al grano.',
	'NO ANDES CON RODEOS. No titubees. Los "Uhm" y "eh" no dan una aura de inteligencia.',
	'Usa un lenguaje preciso y conciso. No estás lanzando a un VC que te preguntará cuál es tu "ingrediente secreto".',
	'Él habla rápidamente, y lo mismo hacen los otros socios de YC. Intenta igualar su ritmo (como deberías al hablar con cualquiera).'
];
